package org.folio.rest.impl;

import io.vertx.core.json.JsonObject;
import org.jetbrains.annotations.NotNull;
import org.junit.jupiter.api.Test;

import java.net.MalformedURLException;

import static org.folio.rest.utils.TestEntities.INVOICE;
import static org.junit.Assert.assertTrue;

public class BatchVoucherTest extends TestBase {
  private static final String ID = "id";
  private static final String BATCH_VOUCHER_ENDPOINT = "/batch-voucher-storage/batch-vouchers";

  @Test
  public void testShould_CreateBatchVoucher_IfRequestBodyIsCorrect_And_IdProvided() throws MalformedURLException {
    JsonObject batchVoucher = createBatchVoucherJSON("data/vouchers/correctBatchVoucher.json");

    String actBatchVoucherId = postData(BATCH_VOUCHER_ENDPOINT, batchVoucher.toString())
                                  .then().log().ifValidationFails()
                                  .statusCode(201)
                                  .extract()
                                  .path(ID);
    assertTrue("Should create batch voucher", actBatchVoucherId.equals(batchVoucher.getString(ID)));
  }

  @Test
  public void testShould_CreateBatchVoucher_IfRequestBodyIsCorrect_And_IdIsNotProvided() throws MalformedURLException {
    JsonObject batchVoucher = createBatchVoucherJSON("data/vouchers/correctBatchVoucher.json");
    batchVoucher.remove(ID);
    String actBatchVoucherId = postData(BATCH_VOUCHER_ENDPOINT, batchVoucher.toString())
                                  .then().log().ifValidationFails()
                                  .statusCode(201)
                                  .extract()
                                  .path(ID);
    assertTrue("Should create batch voucher whit Id generated by server", !actBatchVoucherId.isEmpty());
  }

  @NotNull
  private JsonObject createBatchVoucherJSON(String path) {
    String invoiceSample = getFile(path);
    return new JsonObject(invoiceSample);
  }
}
