#%RAML 1.0
title: "Adjustment Presets"
baseUri: https://github.com/folio-org/mod-invoice-storage
version: v1.0

documentation:
  - title: Adjustment Presets
    content: <b>CRUD APIs used to manage Adjustment Presets for mod-invoice.</b>

types:
  adjustment_preset: !include acq-models/mod-invoice-storage/schemas/adjustment_preset.json
  adjustment_preset_collection: !include acq-models/mod-invoice-storage/schemas/adjustment_preset_collection.json
  errors: !include raml-util/schemas/errors.schema
  error: !include raml-util/schemas/error.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/invoice-storage/adjustment-presets:
  type:
    collection:
      exampleCollection: !include acq-models/mod-invoice-storage/examples/adjustment_preset_collection.sample
      exampleItem: !include acq-models/mod-invoice-storage/examples/adjustment_preset.sample
      schemaCollection: adjustment_preset_collection
      schemaItem: adjustment_preset
  get:
    description: Get a list of adjustment presets
    is: [
      searchable: { description: "CQL query", example: "description==preset1" },
      pageable
    ]
  post:
    description: Add a new adjustment preset
    body:
      application/json:
        type: adjustment_preset
        example:
          strict: false
          value: !include acq-models/mod-invoice-storage/examples/adjustment_preset.sample
    responses:
      201:
        description: Adjustment Preset added
        body:
          application/json:
            example: !include acq-models/mod-invoice-storage/examples/adjustment_preset.sample
      400:
        description: Bad Request
        body:
          application/json:
            type: error
      401:
        description: Not found
        body:
          application/json:
            type: error
      500:
        description: Internal error
        body:
          application/json:
            type: error
  /{id}:
    uriParameters:
      id:
        description: The UUID of the adjustment preset
        type: UUID
    displayName: Adjustment Presets
    description: Get, Delete or Update a specific adjustment preset
    type:
      collection-item:
        exampleItem: !include acq-models/mod-invoice-storage/examples/adjustment_preset.sample
        schema: adjustment_preset
