#%RAML 1.0

title: Batch voucher export configurations
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/folio-org/mod-invoice-storage

documentation:
  - title: Batch voucher export configurations CRUD API
    content: This documents the API calls that can be made to manage batch voucher export configurations; This API is intended for internal use only

types:
  exportConfig: !include acq-models/mod-invoice-storage/schemas/export_configuration.json
  exportConfigCollection: !include acq-models/mod-invoice-storage/schemas/export_configuration_collection.json
  credentials: !include acq-models/mod-invoice-storage/schemas/credentials.json
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/batch-voucher-storage/export-configurations:
    type:
      collection:
        schemaCollection: exportConfigCollection
        schemaItem: exportConfig
        exampleCollection: !include acq-models/mod-invoice-storage/examples/export_configuration_collection.sample
        exampleItem: !include acq-models/mod-invoice-storage/examples/export_configuration.sample
    get:
      description: Get list of batch voucher export configurations
      is: [
        pageable,
        searchable: {description: "with valid searchable fields: for example format", example: "format==\"Application/xml\""}
      ]
    /{id}:
      uriParameters:
        id:
          description: The UUID of a batch voucher export configuration
          type: UUID
      type:
        collection-item:
          schema: exportConfig
          exampleItem: !include acq-models/mod-invoice-storage/examples/export_configuration.sample
      /credentials:
        displayName: Batch Voucher Export Configuration Credentials
        description: Manage Batch Voucher Export Configuration Credentials
        type:
          collection-item:
            schema: credentials
            exampleItem: !include acq-models/mod-invoice-storage/examples/credentials.sample
        post:
          description: Create credentials for a batch voucher configuration
          body:
            application/json:
              type: credentials
              example:
                strict: false
                value: !include acq-models/mod-invoice-storage/examples/credentials.sample
          responses:
            201:
              description: "Returns the newly created credentials, with server-controlled fields like 'id' populated"
              headers:
                Location:
                  description: URI to the created credentials
              body:
                application/json:
                  example: !include acq-models/mod-invoice-storage/examples/credentials.sample
            400:
              description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
              body:
                text/plain:
                  example: "unable to add credentials -- malformed JSON at 13:3"
            401:
              description: "Not authorized to perform requested action"
              body:
                text/plain:
                  example: "unable to create credentials -- unauthorized"
            500:
              description: "Internal server error, e.g. due to misconfiguration"
              body:
                text/plain:
                  example: "Internal server error, contact administrator"
