#%RAML 1.0
title: "Invoice Storage"
baseUri: http://github.com/folio-org/mod-invoice-storage
version: v1

documentation:
  - title: Invoice Number
    content: <b>API used to manage invoice number.</b>

types:
  sequenceNumber: !include acq-models/common/schemas/sequence_number.json

/invoice-storage/invoice-number:
    get:
      description: Get generated invoice number
      responses:
        200:
          body:
            application/json:
              type: sequenceNumber
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "internal server error, contact administrator"

